CREATE TABLE IDN_PASSWORD_HISTORY_DATA (
  ID SERIAL,
  USER_NAME   LVARCHAR(255) NOT NULL,
  USER_DOMAIN LVARCHAR(255) NOT NULL,
  TENANT_ID   INTEGER DEFAULT -1,
  SALT_VALUE  LVARCHAR(255),
  HASH        LVARCHAR(255) NOT NULL,
  TIME_CREATED DATETIME YEAR TO SECOND NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE(USER_NAME,USER_DOMAIN,TENANT_ID,SALT_VALUE,HASH),
  );
